name: "Run jq scripts"
description: "A reusable homebrew formula action that checks out a taps code and updates the given formula"

inputs:
  json-file:
    description: "The target branch of the formula; will create a pull request to it"
    required: false
    default: "main"
  jq-file:
    description: "The target branch of the formula; will create a pull request to it"
    required: false
    default: "main"
  argjson:
    description: "The target branch of the formula; will create a pull request to it"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup jq
      uses: vegardit/setup-jq-action@v1
      with:
        version: 1.7

    # TODO: Create step to install sponge
    # TODO: Create step to validate json object is valid json
    # TODO: Create step to validate json object against schema
    # TODO: Create step to verify json file exists
    # TODO: Create step to verify jq script file exists

    - name: Run jq script
      shell: bash
      run: |
        jq ${{ inputs.argjson }} -f ${{ inputs.jq-file }} ${{ inputs.json-file }} | sponge ${{ inputs.json-file }}
