name: Update Formulas

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      force:
        description: "Force update even if no new release"
        required: false
        default: false
        type: boolean

jobs:
  load-existing-formulas:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      has_updates: ${{ steps.check_updates.outputs.has_updates }}
      existing: ${{ steps.formulas.outputs.unique }}
      repos: ${{ steps.repos.outputs.unique }}
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4

      # Setup JQ
      - name: JQ #
        uses: aRustyDev/gha/actions/run-jq
        with:
          jq-file: .github/jq/parse-formula.jq
          json-file: .data/formula.json
          formula: ${{ inputs.formula }}

      # Get unique formulas
      - name: Unique Formulas #
        id: formulas
        uses: aRustyDev/gha/actions/run-jq
        with:
          jq-file: .github/jq/parse-formula.jq
          json-file: .data/formula.json
          formula: ${{ inputs.formula }}

      # Get unique repos
      - name: Unique Repos #
        id: repos
        uses: aRustyDev/gha/actions/run-jq
        with:
          jq-file: .github/jq/parse-formula.jq
          json-file: .data/formula.json
          formula: ${{ inputs.formula }}

  # Use the GH API to check target repos for new releases/tags
  identify-gaps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      has_updates: ${{ steps.check_updates.outputs.has_updates }}
      formulas: ${{ steps.check_updates.outputs.updates }}
    strategy:
      matrix:
        repos: ${{ jobs.load-existing-formulas.outputs.repos }}
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4

      - name: Setup jq
        uses: vegardit/setup-jq-action@v1
        with:
          version: 1.7

      # Check each formula for updates
      - name: Check formula updates
        id: check_releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: aRustyDev/gha/actions/check-formula
        with:
          formulas: ${{ matrix.repos }}

  # Use the GH API to check target repos for new releases/tags
  update-missing:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      has_updates: ${{ steps.check_updates.outputs.has_updates }}
      formulas: ${{ steps.check_updates.outputs.updates }}
    strategy:
      matrix:
        repos: ${{ jobs.identify-gaps.outputs.missing }}
        versions: ${{ jobs.identify-gaps.outputs.versions }}
    steps:
      # Check each formula for updates
      - name: Update formula
        id: check_releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: aRustyDev/gha/actions/update-formula
        with:
          formulas: ${{ matrix.repos }}
